### PR TITLE
FdfFile > Encode field name / key as UTF-16BE

### PR DESCRIPTION
**Pull request by mcdope**
Works same like the actual value. This allows field names containing german umlauts and most likely many other "special" characters

Closes issue #17 (https://github.com/mikehaertl/php-pdftk/issues/17)

### CODE REVIEW

**Comment by mikehaertl** [comment]
Awesome. Do you think, you could maybe also add a test case for this?

**Comment by mcdope** [comment]
I never touched unittests, not sure... I'll try, but no promises.

**Comment by mikehaertl** [comment]
Hmm, I see. Maybe we can live without for now (even though it would be better to have a test). There should be  a new `testCanCreateFdfFileFromData` test, which is missing anyway.

Up to you, if you want to give it a try. You could add another result file to tests/results and compare it with the file you have generated during the test.

**Comment by mikehaertl** [comment]
Oh, and about the tests: You only need phpunit installed. Then you should be able to just enter `phpunit` in the root directory of the project.

**Comment by mcdope** [comment]
Well, some day I must learn them anyway - even if I'm happy with "write a quick cli script calling stuff and see if it runs" :D I'll give it a try.

Btw, while testing I've also noticed that this no-info error message from getError() also occurs if pdftk isn't installed at all (tested on another comp). Shouldn't that throw some specific message?

**Comment by mikehaertl** [comment]
Which error exactly do you mean?

**Comment by mcdope** [comment]
"Failed without error message"

**Comment by mikehaertl** [comment]
Hmm. That's genereated here: https://github.com/mikehaertl/php-shellcommand/blob/master/src/Command.php. Not sure, why this would happen if the command is not found. Because in this case `proc_open()` should have failed and `is_process()` thus return false. 

Feel free to improve this, but this probably needs fixing in my other project.

**Comment by mcdope** [comment]
Guess Ubuntus "show message telling to install package X" feature on missing commands could be part of it. Don't know how it's realized but could imagine its like "command x not there, run y to tell user he should install z" so that in the end still something gets executed. 

But I don't care enough to investigate that deeper, it's an edge case anyway - usually nobody (sane) would try to use your lib without having pdftk installed...

**Comment by mcdope** [comment]
I've got phpunit running, but I already now get 4 failed tests: PdfTest::testCanCreateFdfFileFromPdf,  PdfTest::testCanFillFormFromData, PdfTest::testCanFillFormFromFile and PdfTest::testCanGetData - all with message "Failed asserting that two strings are equal.". Posted the log here: https://paste.mcdope.org/pvop9jfz8

Is this to be expected? Guess it's caused by running another version of pdftk?

**Comment by mikehaertl** [comment]
Yes, very likely. I've run the test with pdftk 2.02 and they run fine for me. Also check the output of travis, where the tests also succeed: https://travis-ci.org/mikehaertl/php-pdftk/builds/58895526

**Comment by mikehaertl** [comment]
If in doubt, you can also commit and let travis do the work for you. It will do another test run each time you commit.

**Comment by mcdope** [comment]
Since travis is fine it will be the version, will just ignore it. But quite unsure on what exactly the test should do. just checking if the file was written is pointless, isn't it?

**Comment by mcdope** [comment]
Not sure what else to add to the test. So if you have no proposals/wishes for it anymore: done.

**Comment by mikehaertl** [comment]
Thanks!

**Pull request merged**
