### PR TITLE
Pdf::updateInfo() -- make it understand the output of Pdf::getData()

### PR DESCRIPTION
**Pull request by rotdrop**
See #291

### CODE REVIEW

**Comment by mikehaertl** [comment]
> Why then is it that updateInfo() accepts this InfoFile input at all?

It's `pdfk` that needs an infofile for `update_info`. As PHP arrays are usually the most convenient format to work with we used this as input for `updateInfo()` - and use the `InfoFile` class to create the (temporary) infofile for `pdftk` from that array data.

> Why not the entire part of the array which is provided by getData()? 

The entire array is nothing else than the parsed output of `dump_data`. That's what the `InfoFields` class does. So both, array and string, should be absolutely equivalent. And the `InfoFile` instance keeps a copy of the original output from `dump_data` which you can get via `(string) $data` (or `$data->__toString()`).

> Also: changing the formatted array data of getData() is somewhat easier then fiddling with the string output.

Well, you pointed out that `pdftk` expects the input for `update_info` to be in the same format as it returns from `dump_data`. 

I agree that this would make sense. I missed that part in the man page. But if that is true then we really want to create a temporay infofile with the original unmodified string as it is returned by `dump_data`. There should be no conversion required whatsoever.

If you're still not convinced I could also try a quick implementation so you could try it. Would you find time to test it then?

**Comment by rotdrop** [comment]
Well, I actually want to add bookmarks, it is more convenient to add those to the data array provided by getData(), so I then changed the InfoFile class to not only understand the 'Info' part of the array provided by getData() but just the entire output, including the bookmark data.

**Comment by mikehaertl** [comment]
My main problem is really that your changes break BC (see #291).

But in any case it would be good if you could include a test case for your change in `tests/InfoFileTest.php`. Preferably as addition to the existing test in tests/InfoFileTest (which will break now unless we find a solution to keep BC). 

It's much easier to discuss changes if we can see what is the expected input/output.

**Comment by mikehaertl** [comment]
Closing this in favour of #297

**Pull request closed without merging**
