### PR TITLE
Multi-character handle support

### PR DESCRIPTION
**Pull request by wibleh**
As per pdftk 1.45+.  Tested in php 5.2 and 5.5.

### CODE REVIEW

**Comment by mikehaertl** [comment]
Hmm, maybe I can't see it, but how would this ever return 'AA' after 'Z'? My idea was rather to use `base_convert($this->_handle++, 10, 26)` followed by a `strtr()` which replaces 0->A, 1->B, ... A->K, ...

**Comment by mikehaertl** [comment]
Also the tests need to be updated, see: https://travis-ci.org/mikehaertl/php-pdftk/builds/55006791

**Comment by wibleh** [comment]
I was thinking of base_convert! Struggled to get something working properly though (bit busy at this end unfortunately).

Try the following code to test the string incrementing:

php -r "$c = 'A'; for ($i=0; $i<1000; $i++) echo $c++.PHP_EOL;

**Comment by wibleh** [comment]
Also, didn't see the tests - sorry :(

**Comment by mikehaertl** [comment]
Oh, cool. Didn't know that PHP does this :). Anyway, could you please check the test cases? You probably only need to replace the placeholders which started from Z, Y, X, ... before.

**Comment by mikehaertl** [comment]
... and btw thanks for your work. There's no hurry at all, but would be great if the PR also contained the working test cases.

**Comment by wibleh** [comment]
Looking into it.  Have to init a vagrant box to run the tests on, but this is all good learning for me - great to be admitting this in public :-/

**Comment by mikehaertl** [comment]
Don't worry about the tests locally - just update the code and push. Travis will do the rest for you. Fixing the tests should really be a simple matter of replacing Z -> A, ...

**Comment by wibleh** [comment]
Well, the Travis CI build passed but my local PHPUnit tests are still failing in areas:

FAILURES!
Tests: 36, Assertions: 183, Failures: 9.
...F.......FFF..FFF...............FF

**Comment by mikehaertl** [comment]
Any failure error messages? It could probably be because on the travis server it's pdftk 1.44 if i remember correctly.

**Comment by wibleh** [comment]
[vagrant@localhost vagrant]$ ./phpunit.phar
PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

Configuration read from /vagrant/phpunit.xml.dist

...F.......FFF..FFF...............FF

Time: 32.33 seconds, Memory: 6.75Mb

There were 9 failures:

1) CommandTest::testCanAddPageRanges
Failed asserting that false is true.

/vagrant/tests/CommandTest.php:86

2) PdfTest::testCanCatFile
Failed asserting that false is true.

/vagrant/tests/PdfTest.php:163

3) PdfTest::testCanCatFiles
Failed asserting that false is true.

/vagrant/tests/PdfTest.php:189

4) PdfTest::testCanShuffleFiles
Failed asserting that false is true.

/vagrant/tests/PdfTest.php:215

5) PdfTest::testCanCreateFdfFileFromPdf
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-Binary String: 0x254644462d312e320a25e2e3cfd30a312030206f626a200a3c3c0a2f464446                                                                                                                   200a3c3c0a2f4669656c6473205b0a3c3c0a2f562028feff004a00fc007200670065006e0020015c                                                                                                                   6e00e10072006b00610020015c6e015c6601070106011101100020043c043804400430043d043e29                                                                                                                   0a2f5420286e616d65290a3e3e200a3c3c0a2f5620287465737440656d61696c2e636f6d290a2f54                                                                                                                   2028656d61696c290a3e3e200a3c3c0a2f56202f320a2f542028726164696f2031290a3e3e200a3c                                                                                                                   3c0a2f56202f5965730a2f542028636865636b626f782031290a3e3e200a3c3c0a2f56202f300a2f                                                                                                                   542028636865636b626f782032290a3e3e5d0a3e3e0a3e3e0a656e646f626a200a747261696c6572                                                                                                                   0a0a3c3c0a2f526f6f742031203020520a3e3e0a2525454f460a
+Binary String: 0x254644462d312e320a25e2e3cfd30a312030206f626a200a3c3c0a2f464446                                                                                                                   200a3c3c0a2f4669656c6473205b0a3c3c0a2f562028feff004a00fc007200670065006e0020015c                                                                                                                   6e00e10072006b00610020015c6e015c6601070106011101100020043c043804400430043d043e29                                                                                                                   0a2f542028feff006e0061006d0065290a3e3e200a3c3c0a2f562028feff00740065007300740040                                                                                                                   0065006d00610069006c002e0063006f006d290a2f542028feff0065006d00610069006c290a3e3e                                                                                                                   200a3c3c0a2f56202f320a2f542028feff0072006100640069006f00200031290a3e3e200a3c3c0a                                                                                                                   2f56202f5965730a2f542028feff0063006800650063006b0062006f007800200031290a3e3e200a                                                                                                                   3c3c0a2f56202f300a2f542028feff0063006800650063006b0062006f007800200032290a3e3e5d                                                                                                                   0a3e3e0a3e3e0a656e646f626a200a747261696c65720a0a3c3c0a2f526f6f742031203020520a3e                                                                                                                   3e0a2525454f460a

/vagrant/tests/PdfTest.php:268

6) PdfTest::testCanFillFormFromData
Failed asserting that false is true.

/vagrant/tests/PdfTest.php:289

7) PdfTest::testCanFillFormFromFile
Failed asserting that false is true.

/vagrant/tests/PdfTest.php:311

8) PdfTest::testCanGetData
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'InfoBegin
-InfoKey: Creator
+'InfoKey: Creator
 InfoValue: Writer
-InfoBegin
 InfoKey: Producer
 InfoValue: LibreOffice 4.2
-InfoBegin
 InfoKey: CreationDate
 InfoValue: D:20140709121536+02'00'
-PdfID0: 8b93f76a0b28b720d0dee9a6eb2a780a
-PdfID1: 8b93f76a0b28b720d0dee9a6eb2a780a
-NumberOfPages: 5
-PageMediaBegin
-PageMediaNumber: 1
-PageMediaRotation: 0
-PageMediaRect: 0 0 595 842
-PageMediaDimensions: 595 842
-PageMediaBegin
-PageMediaNumber: 2
-PageMediaRotation: 0
-PageMediaRect: 0 0 595 842
-PageMediaDimensions: 595 842
-PageMediaBegin
-PageMediaNumber: 3
-PageMediaRotation: 0
-PageMediaRect: 0 0 595 842
-PageMediaDimensions: 595 842
-PageMediaBegin
-PageMediaNumber: 4
-PageMediaRotation: 0
-PageMediaRect: 0 0 595 842
-PageMediaDimensions: 595 842
-PageMediaBegin
-PageMediaNumber: 5
-PageMediaRotation: 0
-PageMediaRect: 0 0 595 842
-PageMediaDimensions: 595 842'
+PdfID0: 8b93f76ab28b720d0dee9a6eb2a78a
+PdfID1: 8b93f76ab28b720d0dee9a6eb2a78a
+NumberOfPages: 5'

/vagrant/tests/PdfTest.php:546

9) PdfTest::testCanGetDataFields
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 '---
 FieldType: Button
 FieldName: checkbox 1
 FieldFlags: 0
 FieldValue: On
 FieldJustification: Left
 FieldStateOption: Off
 FieldStateOption: On
 ---
 FieldType: Button
 FieldName: checkbox 2
 FieldFlags: 0
 FieldValue: On
 FieldJustification: Left
 FieldStateOption: Off
 FieldStateOption: On
 ---
 FieldType: Button
 FieldName: radio 1
 FieldFlags: 49152
 FieldValue: 2
 FieldJustification: Left
 FieldStateOption: 1
 FieldStateOption: 2
 FieldStateOption: Off
 ---
 FieldType: Text
 FieldName: email
 FieldFlags: 0
 FieldJustification: Left
 ---
 FieldType: Text
 FieldName: name
 FieldFlags: 0
 FieldJustification: Left'

/vagrant/tests/PdfTest.php:556

FAILURES!
Tests: 36, Assertions: 183, Failures: 9.

**Comment by mikehaertl** [comment]
Since the travis tests pass, I've merged it.

As I've said, it's probably because you have a different pdftk version locally. They've changed the orientation names from "east", "north", ... to "E", "N", ... and so on. That's why execution probably fails for you.

**Comment by mikehaertl** [comment]
Also tested locally here with pdftk 2.02 and the tests run fine here.

So thanks again!

**Comment by wibleh** [comment]
Sorry - long day, getting my versions mixed up: 2.02 on cygwin, 1.44 on centos6 via a repo, just tested with 2.02 on centos6 and fared a bit better:

PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

Configuration read from /vagrant/phpunit.xml.dist

....E.............................FF

Time: 37.67 seconds, Memory: 6.50Mb

There was 1 error:

1) PdfTest::testCanPassDocumentToConstructor
copy(/vagrant/tests/test.pdf): failed to open stream: Protocol error

/vagrant/src/Pdf.php:491
/vagrant/tests/PdfTest.php:24

--

There were 2 failures:

1) PdfTest::testCanGetData
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 'InfoBegin
 InfoKey: Creator
 InfoValue: Writer
 InfoBegin
 InfoKey: Producer
 InfoValue: LibreOffice 4.2
 InfoBegin
 InfoKey: CreationDate
 InfoValue: D:20140709121536+02'00'
 PdfID0: 8b93f76a0b28b720d0dee9a6eb2a780a
 PdfID1: 8b93f76a0b28b720d0dee9a6eb2a780a
 NumberOfPages: 5
 PageMediaBegin
 PageMediaNumber: 1
 PageMediaRotation: 0
 PageMediaRect: 0 0 595 842
 PageMediaDimensions: 595 842
 PageMediaBegin
 PageMediaNumber: 2
 PageMediaRotation: 0
 PageMediaRect: 0 0 595 842
 PageMediaDimensions: 595 842
 PageMediaBegin
 PageMediaNumber: 3
 PageMediaRotation: 0
 PageMediaRect: 0 0 595 842
 PageMediaDimensions: 595 842
 PageMediaBegin
 PageMediaNumber: 4
 PageMediaRotation: 0
 PageMediaRect: 0 0 595 842
 PageMediaDimensions: 595 842
 PageMediaBegin
 PageMediaNumber: 5
 PageMediaRotation: 0
 PageMediaRect: 0 0 595 842
 PageMediaDimensions: 595 842'

/vagrant/tests/PdfTest.php:546

2) PdfTest::testCanGetDataFields
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 '---
 FieldType: Button
 FieldName: checkbox 1
 FieldFlags: 0
 FieldValue: On
 FieldJustification: Left
 FieldStateOption: Off
 FieldStateOption: On
 ---
 FieldType: Button
 FieldName: checkbox 2
 FieldFlags: 0
 FieldValue: On
 FieldJustification: Left
 FieldStateOption: Off
 FieldStateOption: On
 ---
 FieldType: Button
 FieldName: radio 1
 FieldFlags: 49152
 FieldValue: 2
 FieldJustification: Left
 FieldStateOption: 1
 FieldStateOption: 2
 FieldStateOption: Off
 ---
 FieldType: Text
 FieldName: email
 FieldFlags: 0
 FieldJustification: Left
 ---
 FieldType: Text
 FieldName: name
 FieldFlags: 0
 FieldJustification: Left'

/vagrant/tests/PdfTest.php:556

FAILURES!
Tests: 36, Assertions: 198, Failures: 2, Errors: 1.

**Comment by mikehaertl** [comment]
Hmm, not sure what's wrong. But definitely related to your setup. The tests may not be 100% perfect anyway. But if they run on travis and on my host here I'm satisfied.

Testing with travis is painful anyway, as they still don't even support ubuntu 14.04. I had a hard time to make it work there and won't touch it any time soon again ;).

**Pull request merged**
