### PR TITLE
Fix for "Undefined offset: 26" error

### PR DESCRIPTION
**Pull request by wibleh**
Zero indexed array produced from range(), with indexes of 0-25 for the
26 characters.

### CODE REVIEW

**Comment by mikehaertl** [comment]
Nice, thanks!

**Comment by wibleh** [comment]
You're welcome, glad to have finally popped my github cherry rather than sending someone else to do it!  Looking at the Pdf::getHandle() method, it would be a good idea to look at changing it to allow more than 26 handles.

**Comment by mikehaertl** [comment]
Yeah, actually I already had this before (it returned AA, AB, AC, ..., BA, BB, ...) But then I found out, that with pdftk 1.x you can't have more than A-Z. :(. This should probably be configurable...

**Comment by wibleh** [comment]
Just read the changelog for pdftk and multi-character handles were added in v1.45 (released 6 Dec 2012:
"You can now use multi-character input handles. Prior versions were limited to a single character, imposing an arbitrary limitation on the number of input PDFs when using handles. Handles still must be all upper-case ASCII."

Liking the idea of configuring multi-character handles though, maybe a allowMulticharacterHandles() method?

**Comment by mikehaertl** [comment]
How about this: We let the method return (A, B, C, ... AA, AB, AC, ...,AAA, AAB, ...). So even if pdftk only supports A-Z it will still work for up to 26 handles (which is the maximum for those versions anyway...)

**Comment by wibleh** [comment]
Sounds good.  The description for this project does state that it's for v2.x so that covers any issues if it breaks (though if people are trying to combine more than 26 pdfs it wouldn't work for them anyway).

**Pull request merged**
