### PR TITLE
Add new operation - attachFiles() - to handle adding attachments into file

### PR DESCRIPTION
**Pull request by mu4ddi3**
Examples  in readme

### CODE REVIEW

**Comment by mikehaertl** [comment]
@mu4ddi3 Sorry for the delay. I'm quite busy at the moment so it may take a little until I find time to study the changes. Let me know if you're in a hurry, then I'll try to find some spare time sooner.

**Comment by mu4ddi3** [comment]
No problem, it's your library. I can wait, and for now i'll use my local modified version for current project.

**Comment by mikehaertl** [comment]
@mu4ddi3 Sorry for letting you wait so long. I like your addition but I think we can rewrite it a little. I'll add some notes. Maybe you can comment on them.

If you have no time for discussion or can't help testing, maybe you can also drop me a quick note here.

**Comment by mu4ddi3** [comment]
Hi @mikehaertl, i made a little comment on php-shellcommand, answering your proposition. Do you have any other proposition to change something here in php-pdftk repo?

**Comment by mikehaertl** [comment]
@mu4ddi3 Hmm, I think my comments here are not really related to the planned changes in shellcommand.

**Comment by mikehaertl** [comment]
`attachFiles()` was added in 0.11.0

**Pull request closed without merging**
